### ISSUE TITLE
無法選擇螢幕亮度的鍵值

### ISSUE THREAD

**Issue by Darktt** [ln-org/lne_link#1]
在 VIA 上可以設定這個功能，但是在 Link 上沒找到
<img width="185" alt=" 2022-01-03 06 58 10" src="https://user-images.githubusercontent.com/4329011/147891658-a16981e0-3cdb-4760-82af-7eb27969f692.png">

另外宏是否能提供直接按鍵輸入的功能，直接用滑鼠點選按鍵沒那麼直覺。

**Comment by NWIron** [comment]
1. 我们已经添加了更多**系统交互**的按键，包括提到的屏幕亮度控制。
2. 我们会考虑在未来重新设计宏的交互方式。
