### ISSUE TITLE
宏命令功能增强需求

### ISSUE THREAD

**Issue by siliscar** [ln-org/lne_link#3]
宏命令刚需用户，发现以下问题。

1. 无法通过宏输出类似 aBc 之类的字符串，家属shift按键后的所有按键都会变为大写。
2. 一个宏命令最多只能输出6个字符，但是编辑时可以写入多个字符。
3. 无法在宏命令中加入delay之类的功能性命令。

**Comment by NWIron** [comment]
宏功能块已经重构基本完毕，考虑到via的通信协议，暂时搁置delay的功能命令。
